# Streamlit Secrets Template
# Copy this to .streamlit/secrets.toml for local development
# Add your actual tokens in Streamlit Cloud's secrets management

# Hugging Face API Token
# Get from: https://huggingface.co/settings/tokens
HF_TOKEN = "your_hugging_face_token_here"

# Optional: OpenAI API Key (if you want to use GPT models)
# OPENAI_API_KEY = "your_openai_key_here"